(source melpa)

(depends-on "cargo")
(depends-on "darktooth-theme")
(depends-on "lsp-mode")
(depends-on "lsp-rust")
(depends-on "lsp-ui")
(depends-on "pallet")
(depends-on "rainbow-delimiters")
(depends-on "rainbow-identifiers")
(depends-on "rust-mode")
(depends-on "zenburn-theme")
